config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  root to:"home#index"
  

  
  resources :profiles do
    resources :orders do
      resources :order_items
    end
  end
  
  resources :orders do
      resources :order_items
  end
  
  
  

end

app/models/order.rb
class Order < ActiveRecord::Base
  belongs_to :profile
  has_many :order_items
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  # GET profile/orders.json
  def index
    @profile = Profile.find(params[:profile_id])
    @orders = @profile.orders
  end

  # GET /orders/1
  # GET /orders/1.json
  def show
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.find(params[:id])
  end

  # GET /orders/new
  def new
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.build
  end

  # GET /orders/1/edit
  def edit
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.find(params[:id])
  end

  # POST /orders
  # POST /orders.json
  def create
    #@order = Order.new(order_params)

    #respond_to do |format|
     # if @order.save
      #  format.html { redirect_to @order, notice: 'Order was successfully created.' }
       # format.json { render :show, status: :created, location: @order }
      #else
       # format.html { render :new }
        #format.json { render json: @order.errors, status: :unprocessable_entity }
      #end
    #end 
    
    @profile = Profile.find(params[:profile_id])
    @order = @profile.orders.build(params.require(:order).permit(:pickUpTime, :totalPrice))
    if @order.save
      redirect_to profile_order_url(@profile, @order), notice: "Order was successfully created."
    else
      render :action => "new"
    end
  end

  # PATCH/PUT /orders/1
  # PATCH/PUT /orders/1.json
  def update
    #respond_to do |format|
      #if @order.update(order_params)
        #format.html { redirect_to @order, notice: 'Order was successfully updated.' }
        #format.json { render :show, status: :ok, location: @order }
      #else
       # format.html { render :edit }
        #format.json { render json: @order.errors, status: :unprocessable_entity }
      #end
    #end
    
    @profile = Profile.find(params[:profile_id])
    @order = Order.find(params[:id])
    if @order.update_attributes(params.require(:order).permit(:pickUpTime, :totalPrice))
      redirect_to profile_order_url(@profile, @order)
    else
      render :action => "edit"
    end
  end

  # DELETE /orders/1
  # DELETE /orders/1.json
  def destroy
    @profile = Profile.find(params[:profile_id])
    @order = Order.find(params[:id])
    @order.destroy
    respond_to do |format|
      format.html { redirect_to profile_orders_path(@profile), notice: 'Order was successfully destroyed.' }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_params
      params.require(:order).permit(:pickUpTime, :totalPrice, :profile_id)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_for([@profile, @order]) do |f| %>
  <% if @order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
      <% @order.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :pickUpTime %><br>
    <%= f.time_select :pickUpTime %>
  </div>
  <div class="field">
    <%= f.label :totalPrice %><br>
    <%= f.text_field :totalPrice %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form' %>

<%= link_to 'Show', profile_order_path(@profile, @order) %> |
<%= link_to 'Back', profile_orders_path(@profile) %> |
<%= link_to 'New Order item', new_profile_order_order_item_path(@profile, @order, @order_items) %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Orders for <%=@profile.firstname%></h1>

<table>
  <thead>
    <tr>
      <th>Pickuptime</th>
      <th>Totalprice</th>
      <th>Profile</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @orders.each do |order| %>
      <tr>
        <td><%= order.pickUpTime %></td>
        <td><%= order.totalPrice %></td>
        <td><%= order.profile %></td>
        <td><%= link_to 'Show', profile_order_path(@profile, order) %></td>
        <td><%= link_to 'Edit', edit_profile_order_path(@profile, order) %></td>
        <td><%= link_to 'Destroy', profile_order_path(@profile, order), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Order', new_profile_order_path(@profile, @orders) %>
<%= link_to 'Back to Profile', @profile %>

app/views/orders/new.html.erb
<h1>New Order</h1>
<%= render 'form' %>

<%= link_to 'Back to Profile', profile_orders_path(@profile) %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>Pickuptime:</strong>
  <%= @order.pickUpTime %>
</p>

<p>
  <strong>Totalprice:</strong>
  <%= @order.totalPrice %>
</p>

<p>
  <strong>Profile:</strong>
  <%= @order.profile %>
</p>

<h2>Items</h2>
<% @order.order_items.each do |order_item| %>
<p>
  <%= order_item %>
</p>
<% end %>

<%= link_to 'Edit Order', edit_profile_order_path(@profile, @order) %> |
<%= link_to 'Back to Profile', profile_path(@profile) %> |
<%= link_to 'New Order item', new_profile_order_order_item_path(@profile, @order) %>
<%= link_to 'Show Order Items', profile_order_order_items_path(@profile, @order) %>