config/routes.rb
Rails.application.routes.draw do
  
  devise_for :users
  get 'home/index'
  
  get '/signedinuserprofile' => 'profiles#signedinuserprofile'

  root to:"home#index"
  

  
  resources :profiles do
    resources :orders do
      resources :order_items
    end
  end
  
  resources :orders do
      resources :order_items
  end
  
  
  

end

app/models/order_item.rb
class OrderItem < ActiveRecord::Base
  belongs_to :order
  has_many :menu_items
end

app/controllers/order_items_controller.rb
class OrderItemsController < ApplicationController
  before_filter :authenticate_user!
  before_action :set_order_item, only: [:show, :edit, :update, :destroy]

  # GET /order_items
  # GET /order_items.json
  def index
    @order = Order.find(params[:order_id])
    @order_items = @order.order_items
  end

  # GET /order_items/1
  # GET /order_items/1.json
  def show
    @order = Order.find(params[:order_id])
    @order_item = @order.order_items.find(params[:id])
  end

  # GET /order_items/new
  def new
    @order = Order.find(params[:order_id])
    @order_item = @order.order_items.build
  end

  # GET /order_items/1/edit
  def edit
    @order = Order.find(params[:order_id])
    @order_item = @order.order_items.find(params[:id])
  end

  # POST /order_items
  # POST /order_items.json
  def create
    
    #@profile = Profile.find(params[:profile_id])
    @order = Order.find(params[:order_id])
    @order_item = @order.order_items.build(params.require(:order_item).permit(:id))
    if @order_item.save
      redirect_to order_order_items_url(@order, @order_item), notice: "Items were successfully added."
    else
      render :action => "new"
    end
    
    #@order_item = OrderItem.new(order_item_params)

    #respond_to do |format|
      #if @order_item.save
        #format.html { redirect_to @order_item, notice: 'Order item was successfully created.' }
        #format.json { render :show, status: :created, location: @order_item }
      #else
        #format.html { render :new }
        #format.json { render json: @order_item.errors, status: :unprocessable_entity }
      #end
    #end
    
  end

  # PATCH/PUT /order_items/1
  # PATCH/PUT /order_items/1.json
  def update
    
    @order = Order.find(params[:order_id])
    @order_item = Order_item.find(params[:id])
    if @order_item.update_attributes(params.require(:order_item).permit(:id))
      redirect_to order_order_items_url(@order, @order_item)
    else
      render :action => "edit"
    end
    
    #respond_to do |format|
     # if @order_item.update(order_item_params)
      #  format.html { redirect_to @order_item, notice: 'Order item was successfully updated.' }
       # format.json { render :show, status: :ok, location: @order_item }
      #else
       # format.html { render :edit }
        #format.json { render json: @order_item.errors, status: :unprocessable_entity }
      #end
    #end
  end

  # DELETE /order_items/1
  # DELETE /order_items/1.json
  def destroy
    
    @order = Order.find(params[:order_id])
    @order_item = Order_item.find(params[:id])
    @order_item.destroy
    respond_to do |format|
      format.html { redirect_to order_order_items_path(@order), notice: 'Order list was successfully destroyed.' }
      format.xml { head :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order_item
      @order_item = OrderItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def order_item_params
      params.require(:order_item).permit(:menu_item_id, :order_id)
    end
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/views/order_items/_form.html.erb
<%= form_for([@order, @order_item]) do |f| %>
  <% if @order_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@order_item.errors.count, "error") %> prohibited this order_item from being saved:</h2>

      <ul>
      <% @order_item.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :menu_item_id %><br>
    <%= f.text_field :menu_item_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/order_items/edit.html.erb
<h1>Editing Order Item</h1>

<%= render 'form' %>

<%= link_to 'Show', order_order_item_path(@order, @order_item) %> |
<%= link_to 'Back', order_order_items_path(@order) %>

app/views/order_items/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Order Items</h1>

<table>
  <thead>
    <tr>
      <th>Menu item</th>
      <th>Order</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @order_items.each do |order_item| %>
      <tr>
        <td><%= order_item.menu_items %></td>
        <td><%= order_item.order %></td>
        <td><%= link_to 'Show', profile_order_order_item_path(@profile, @order, order_item) %></td>
        <td><%= link_to 'Edit', edit_profile_order_order_item_path(@profile, @order, order_item) %></td>
        <td><%= link_to 'Destroy', profile_order_order_item_path(@profile, @order, order_item), method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>


<%= link_to 'New Order item', new_profile_order_order_item_path(@profile, @order) %>
<%= link_to 'Back', profile_order_path(@profile, @order) %>

app/views/order_items/new.html.erb
<h1>New Order Item</h1>

<%= render 'form' %>

<%= link_to 'Back', order_order_items_path(@order) %>

app/views/order_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Menu item:</strong>
  <%= @order_item.menu_item %>
</p>

<p>
  <strong>Order:</strong>
  <%= @order_item.order %>
</p>

<%= link_to 'Edit', edit_order_order_item_path(@order, @order_item) %> |
<%= link_to 'Back', profile_order(@profile, @order) %>